{
 "title": "Cloud Spendings",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "REGIONs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT SUM(amount) AS \"value\", source_system AS \"source_system\", region AS \"region\", start_date AS \"time\" FROM clean_spendings GROUP BY source_system, region, start_date LIMIT 50 "
    }
   ]
  },
  {
   "title": "By source system",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT SUM(amount), source_system FROM clean_spendings GROUP BY source_system LIMIT 50 "
    }
   ]
  },
  {
   "title": "By resource group",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "with top_meta as (\n  select resource_group, source_system, sum(amount) amount_sum\n  from clean_spendings\n  where start_date between cast('${__from:date}' as date) and cast('${__to:date}' as date)\n  group by 1,2\n  order by amount_sum desc\n  limit 5\n)\nSELECT SUM(amount) AS \"value\", MIN(cs.source_system) AS \"source_system\", MIN(cs.resource_group) AS \"region\", start_date AS \"time\"\nFROM clean_spendings cs\ninner join top_meta meta on cs.resource_group = meta.resource_group and cs.source_system = meta.source_system\nGROUP BY cs.source_system, cs.resource_group, start_date\norder by start_date desc"
    }
   ]
  }
 ]
}