---
version: '3'
x-airflow-common:
  &airflow-common
  # In order to add custom dependencies or upgrade provider packages you can use your extended image.
  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
  image: ${AIRFLOW_IMAGE_NAME}
 #    build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT: google-cloud-platform://?extra__google_cloud_platform__key_path=%2Fkeys%2Fkey.json&extra__google_cloud_platform__scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&extra__google_cloud_platform__project=${GOOGLE_CLOUD_PROJECT}&extra__google_cloud_platform__num_retries=5
    # AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
#    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW_VAR_GCS_BILLING_BUCKET: ${GCS_BILLING_BUCKET}
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
  volumes:
    - ./dags:/root/airflow/dags
    - ./logs:/root/airflow/logs
    - ./plugins:/root/airflow/plugins
    - ./scripts:/root/scripts
    - ./keys:/keys
  privileged: true
  depends_on:
    &airflow-common-depends-on
   postgres:
      condition: service_healthy
#  user: "${AIRFLOW_UID:-50000}:0"
 
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always
    ports:
    - 5434:5432

  postgres_client:
    image: postgres:13
    environment:
      POSTGRES_USER: local_user
    volumes:
      - postgres-db-volume-client:/var/lib/postgresql/data
      - ./pg_init:/docker-entrypoint-initdb.d
    restart: always 
    env_file: .db.env
    ports: 
      - 5433:5432 

  airflow-web:
    ports: 
    - 8080:8080
    entrypoint: [ "bash", "-c", "airflow webserver --port 8080"]
    <<: *airflow-common
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    entrypoint: [ "bash", "-c", "airflow scheduler"]
    <<: *airflow-common
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .secret.env  

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - /root/scripts/airflow-init-rpi.sh


volumes:
  postgres-db-volume:
  postgres-db-volume-client:
